USE [master]
GO
/****** Object:  Database [spotify]    Script Date: 19/02/2025 18:12:25 ******/
CREATE DATABASE [spotify]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'spotify', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.PATATA\MSSQL\DATA\spotify.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'spotify_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.PATATA\MSSQL\DATA\spotify_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [spotify] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [spotify].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [spotify] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [spotify] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [spotify] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [spotify] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [spotify] SET ARITHABORT OFF 
GO
ALTER DATABASE [spotify] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [spotify] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [spotify] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [spotify] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [spotify] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [spotify] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [spotify] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [spotify] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [spotify] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [spotify] SET  DISABLE_BROKER 
GO
ALTER DATABASE [spotify] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [spotify] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [spotify] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [spotify] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [spotify] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [spotify] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [spotify] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [spotify] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [spotify] SET  MULTI_USER 
GO
ALTER DATABASE [spotify] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [spotify] SET DB_CHAINING OFF 
GO
ALTER DATABASE [spotify] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [spotify] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [spotify] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [spotify] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [spotify] SET QUERY_STORE = ON
GO
ALTER DATABASE [spotify] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [spotify]
GO
/****** Object:  User [sergi]    Script Date: 19/02/2025 18:12:25 ******/
CREATE USER [sergi] FOR LOGIN [sergi] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [sergi]
GO
/****** Object:  Table [dbo].[Playlists]    Script Date: 19/02/2025 18:12:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Playlists](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[UserId] [uniqueidentifier] NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PlaylistSongs]    Script Date: 19/02/2025 18:12:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PlaylistSongs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PlaylistId] [int] NOT NULL,
	[SongId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_PlaylistSong] UNIQUE NONCLUSTERED 
(
	[PlaylistId] ASC,
	[SongId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ratings]    Script Date: 19/02/2025 18:12:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ratings](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [uniqueidentifier] NOT NULL,
	[SongId] [int] NOT NULL,
	[Rating] [int] NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_UserSong] UNIQUE NONCLUSTERED 
(
	[UserId] ASC,
	[SongId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Songs]    Script Date: 19/02/2025 18:12:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Songs](
	[Id] [uniqueidentifier] NOT NULL,
	[Title] [nvarchar](255) NOT NULL,
	[Artist] [nvarchar](255) NOT NULL,
	[UserId] [uniqueidentifier] NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 19/02/2025 18:12:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [uniqueidentifier] NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Password] [nvarchar](255) NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Playlists] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Ratings] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Songs] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[Songs] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[Playlists]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PlaylistSongs]  WITH CHECK ADD FOREIGN KEY([PlaylistId])
REFERENCES [dbo].[Playlists] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Ratings]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Ratings]  WITH CHECK ADD CHECK  (([Rating]>=(1) AND [Rating]<=(5)))
GO
USE [master]
GO
ALTER DATABASE [spotify] SET  READ_WRITE 
GO
